spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/salida?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    # password: 3525

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            trace